// Code generated by zeus-gen. DO NOT EDIT.
package rpc

import (
	"log"

	"github.com/micro/go-micro/server"

	"gitlab.dg.com/BackEnd/jichuchanpin/tif/zeus/service"

	"zeus-examples/hellodemo/global"
	"zeus-examples/hellodemo/handler"
	gomicro "zeus-examples/hellodemo/proto/hellodemopb"
)

func init() {
	// gomicro
	global.ServiceOpts = append(global.ServiceOpts, service.WithGoMicrohandlerRegisterFnOption(gmHelloDemoHandlerRegister))
	global.ServiceOpts = append(global.ServiceOpts, service.WithServiceNameOption("hellodemo"))
}

func gmHelloDemoHandlerRegister(s server.Server, opts ...server.HandlerOption) (err error) {
	if err = gomicro.RegisterHelloDemoHandler(s, handler.NewHelloDemo(), opts...); err != nil {
		log.Println("gomicro.RegisterHelloDemoHandler err:", err)
		return
	}
	return
}

