// Code generated by zeus-gen. DO NOT EDIT.
package proto

import (
	"embed"

	swaggerhelper "github.com/mmqbaba/zeus/swagger"
)

//go:embed *.swagger.json
var swaggerFile embed.FS

func init() {
	swaggerhelper.SetSwaggerfile(swaggerFile)
}
