// Code generated by zeus-gen. DO NOT EDIT.
package http

import (
	"context"
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	gruntime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	zeusmwhttp "github.com/mmqbaba/zeus/middleware/http"
	"github.com/mmqbaba/zeus/service"

	"zeus-examples/hellodemo/global"
	"zeus-examples/hellodemo/handler"
	gw "zeus-examples/hellodemo/proto/hellodemopb"
)

const (
	Route_HelloDemoHdlr_SayHello zeusmwhttp.RouteLink = "Route_HelloDemoHdlr_SayHello"
	Route_HelloDemoHdlr_Get      zeusmwhttp.RouteLink = "Route_HelloDemoHdlr_Get"
	Route_HelloDemoHdlr_Put      zeusmwhttp.RouteLink = "Route_HelloDemoHdlr_Put"
	Route_HelloDemoHdlr_Delete   zeusmwhttp.RouteLink = "Route_HelloDemoHdlr_Delete"
	Route_HelloDemoHdlr_PingPong zeusmwhttp.RouteLink = "Route_HelloDemoHdlr_PingPong"
)

var hellodemoHdlr = &handler.HelloDemo{}
var hellodemoHdlrRoutes = map[zeusmwhttp.RouteLink]*zeusmwhttp.Route{
	Route_HelloDemoHdlr_SayHello: &zeusmwhttp.Route{
		RLink:  Route_HelloDemoHdlr_SayHello,
		Method: http.MethodPost,
		Path:   "/v1/hello",
		Handle: zeusmwhttp.GenerateGinHandle(hellodemoHdlr.SayHello),
	},
	Route_HelloDemoHdlr_Get: &zeusmwhttp.Route{
		RLink:  Route_HelloDemoHdlr_Get,
		Method: http.MethodGet,
		Path:   "/v1/hello",
		Handle: zeusmwhttp.GenerateGinHandle(hellodemoHdlr.Get),
	},
	Route_HelloDemoHdlr_Put: &zeusmwhttp.Route{
		RLink:  Route_HelloDemoHdlr_Put,
		Method: http.MethodPut,
		Path:   "/v1/hello",
		Handle: zeusmwhttp.GenerateGinHandle(hellodemoHdlr.Put),
	},
	Route_HelloDemoHdlr_Delete: &zeusmwhttp.Route{
		RLink:  Route_HelloDemoHdlr_Delete,
		Method: http.MethodDelete,
		Path:   "/v1/hello",
		Handle: zeusmwhttp.GenerateGinHandle(hellodemoHdlr.Delete),
	},
	Route_HelloDemoHdlr_PingPong: &zeusmwhttp.Route{
		RLink:  Route_HelloDemoHdlr_PingPong,
		Method: http.MethodPost,
		Path:   "/v1/pingpong",
		Handle: zeusmwhttp.GenerateGinHandle(hellodemoHdlr.PingPong),
	},
}

func init() {
	// grpc gateway
	global.ServiceOpts = append(global.ServiceOpts, service.WithHttpGWhandlerRegisterFnOption(gwHandlerRegister))
	// http handler
	global.ServiceOpts = append(global.ServiceOpts, service.WithHttpHandlerRegisterFnOption(getHandlerRegisterFn()))
	global.ServiceOpts = append(global.ServiceOpts, service.WithSwaggerJSONFileName("hellodemo"))
}

func gwHandlerRegister(ctx context.Context, endpoint string, opts []grpc.DialOption) (m *gruntime.ServeMux, err error) {
	optsTmp := opts
	mux := gruntime.NewServeMux()
	if len(opts) == 0 {
		optsTmp = []grpc.DialOption{grpc.WithInsecure()}
	}
	if err = gw.RegisterHelloDemoHandlerFromEndpoint(ctx, mux, endpoint, optsTmp); err != nil {
		log.Println("gw.RegisterHelloDemoHandlerFromEndpoint err:", err)
		return
	}
	m = mux
	return
}

func getHandlerRegisterFn() service.HttpHandlerRegisterFn {
	return serveHTTPHandler
}

func registerRoutesForHelloDemoHandler(groups map[string]*gin.RouterGroup, customFn ...zeusmwhttp.CustomRouteFn) {
	for _, f := range customFn {
		f(hellodemoHdlrRoutes)
	}
	for _, r := range hellodemoHdlrRoutes {
		zeusmwhttp.Method(groups, r)
	}
}
