// Code generated by zeus-gen. DO NOT EDIT.
package errdef

import (
	"github.com/mmqbaba/zeus/errors"
	"net/http"
)

// 每个子项目特有的错误码定义，避免使用 0 ~ 19999，与公共库冲突
const (
	ECodeSampleServiceErr errors.ErrorCode = 20001
	ECodeSealServiceErr errors.ErrorCode = 30001
	ECodeSampleInvalidParams errors.ErrorCode = 50001

)

func init() {
	// ECodeMsg and ECodeStatus
	errors.ECodeMsg[ECodeSampleServiceErr] = "SampleServiceErr"
	errors.ECodeStatus[ECodeSampleServiceErr] = http.StatusInternalServerError
	errors.ECodeMsg[ECodeSealServiceErr] = "SampleServiceErr"
	errors.ECodeStatus[ECodeSealServiceErr] = http.StatusInternalServerError
	errors.ECodeMsg[ECodeSampleInvalidParams] = "sample invalid params"
	errors.ECodeStatus[ECodeSampleInvalidParams] = http.StatusOK

}

