// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hello.proto

package hello

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *HelloRequest) Validate() error {
	if !(this.Age > 20) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '20'`, this.Age))
	}
	if !(this.Age < 27) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '27'`, this.Age))
	}
	return nil
}
func (this *HelloReply) Validate() error {
	return nil
}
func (this *PingRequest) Validate() error {
	return nil
}
func (this *PongReply) Validate() error {
	return nil
}
func (this *UploadReq) Validate() error {
	return nil
}
func (this *UploadResp) Validate() error {
	return nil
}
