// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sample.proto

package sample

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/mwitkow/go-proto-validators"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/struct"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Request) Validate() error {
	if !(this.Age > 20) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '20'`, this.Age))
	}
	if !(this.Age < 27) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '27'`, this.Age))
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *Reply) Validate() error {
	return nil
}
func (this *PingRequest) Validate() error {
	return nil
}
func (this *PongReply) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	if this.MetaData != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.MetaData); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("MetaData", err)
		}
	}
	return nil
}
func (this *UploadReq) Validate() error {
	return nil
}
func (this *UploadResp) Validate() error {
	return nil
}
